name: VoltskiyaMobManager
version: 1.0
main: apple.voltskiya.mob_manager.MMVoltskiyaPlugin
api-version: 1.16
authors: [ appleptr16 ]
softdepend: [ LoadDependencies, VoltPluginManager, AppleMCUtil, DecodingNms, VoltskiyaUtilities ]
